logging:
  level:
    root: INFO
    org.springframework: INFO
    com.at.t: DEBUG
  file:
    name: logs/spring-boot-app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
